// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlautherHouse.proto

package via.sdj3.grpcspringbootx.protobuf;

public interface ResponseTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string output_text = 1;</code>
   * @return A list containing the outputText.
   */
  java.util.List<java.lang.String>
      getOutputTextList();
  /**
   * <code>repeated string output_text = 1;</code>
   * @return The count of outputText.
   */
  int getOutputTextCount();
  /**
   * <code>repeated string output_text = 1;</code>
   * @param index The index of the element to return.
   * @return The outputText at the given index.
   */
  java.lang.String getOutputText(int index);
  /**
   * <code>repeated string output_text = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputText at the given index.
   */
  com.google.protobuf.ByteString
      getOutputTextBytes(int index);
}
